CREATE TABLE IF NOT EXISTS KnowLawUserRole (
    id BIGSERIAL PRIMARY KEY,
    roleName VARCHAR(255) NOT NULL
);

INSERT INTO KnowLawUserRole (roleName)
VALUES ('ADMIN_ROLE'), ('PROVIDER_ROLE'), ('CONSUMER_ROLE');